### PR TITLE
Catch errors on load

### PR DESCRIPTION
**Pull request by sdwHunter**
Hi! First of all, thank you for the work you've put in this project.

I've encountered this error when loading a specific KML.

uncaught error

Every load I make afterwards "throws" the same error (actually it's the same rejected promise being revisited again and again)

So this change is to be able to catch the error in the application and to allow to load other files after one load failed

### CODE REVIEW

**Comment by Raruto** [comment]
Hi sdwHunter,
just out of curiosity, can you explain why that file throws an error?

_Raruto_

**Comment by Raruto** [comment]
I close this because the problem you report has already been handled here: https://github.com/Raruto/leaflet-kmz/pull/25
Even merging this change the code would crash if the developer doesn't add a `catch` clause within in his code, so let's leave it like this for now 😄.

_Have a nice day,
Raruto_

**Comment by sdwHunter** [comment]
yeah x) but wouldn't it be now the developer's responsibility to handle those errors?

Another reason I was interested in this was the fact that if the load function fails (invalid file, coordinates, etc), we can no longer do any further loads because it is kind of stuck on a rejected promise. So every new load will "fail" with the same error message, it wouldn't even try to load the new file.

So I have two questions, is there a way to handle those internal errors from the host app? and after it has failed, how can we avoid getting stuck with the same error?

Thank you for your time, work and effort, I really appreciate it. 

Have a nice day as well

**Comment by Raruto** [comment]
Hi swHunter, 

> yeah x) but wouldn't it be now the developer's responsibility to handle those errors?

yes, someone will have to take care of it. I think your modification should be studied in depth for a moment to evaluate better all the consequences of that change.

> Another reason I was interested in this was the fact that if the load function fails (invalid file, coordinates, etc), we can no longer do any further loads because it is kind of stuck on a rejected promise. So every new load will "fail" with the same error message, it wouldn't even try to load the new file.

I guess it "stucks" because you use the same instance of the kmz layer, have you tried to do as shown here? https://github.com/Raruto/leaflet-kmz/pull/21#issuecomment-1056865232

> So I have two questions, is there a way to handle those internal errors from the host app? and after it has failed, how can we avoid getting stuck with the same error?

If you want a quick method it is to override the function whose behavior you want to change:

https://github.com/Raruto/leaflet-kmz/blob/212d94500a94a0058b59a69e6da6b96b39082336/src/KMZLayer.js#L26-L29

In the leaflet guides there are also some examples: https://leafletjs.com/examples/extending/extending-1-classes.html (it's not necessary to create a new derived class).

BTW, if you do a pull that shows some of these edge cases we can also look at them together (if you think it could also be useful for others..).

_Greetings,
Raruto_

**Comment by sdwHunter** [comment]
Hi Raruto, thank you for your reply.

> I guess it "stucks" because you use the same instance of the kmz layer, have you tried to do as shown here? https://github.com/Raruto/leaflet-kmz/pull/21#issuecomment-1056865232

I use a different instance every time. I think the promise is inside the KMZLayer class and so is reused every new load (exactly in that section of code you show above).

> If you want a quick method it is to override the function whose behavior you want to change:

Wow I never thought of this, thank you :)

> BTW, if you do a pull that shows some of these edge cases we can also look at them together (if you think it could also be useful for others..).

The only example file I have is one that I know had something deleted inside, so it's not valid and fails as expected.

It's probably very uncommon for an invalid/malformed file to be used, I think.

I guess I was too focused on trying to catch everything that could fail.

Thank you again

**Pull request closed without merging**
